"""updated permission_model

Revision ID: 1a03d8f96b0c
Revises: 93fdee67ba4d
Create Date: 2026-05-15 23:51:54.135345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a03d8f96b0c'
down_revision: Union[str, Sequence[str], None] = '93fdee67ba4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('can_all_read', sa.Boolean(), nullable=False))
    op.add_column('permissions', sa.Column('can_all_update', sa.Boolean(), nullable=False))
    op.add_column('permissions', sa.Column('can_all_delete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'can_all_delete')
    op.drop_column('permissions', 'can_all_update')
    op.drop_column('permissions', 'can_all_read')
    # ### end Alembic commands ###
