"""add can_all_create

Revision ID: 8c20f76ffe2f
Revises: cf7b785a8f96
Create Date: 2026-05-16 14:52:49.703961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c20f76ffe2f'
down_revision: Union[str, Sequence[str], None] = 'cf7b785a8f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('can_all_create', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'can_all_create')
    # ### end Alembic commands ###
