"""add can_all_create v2

Revision ID: 9ad4987b3c94
Revises: 8c20f76ffe2f
Create Date: 2026-05-16 14:55:36.740303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad4987b3c94'
down_revision: Union[str, Sequence[str], None] = '8c20f76ffe2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'can_all_create',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'can_all_create',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
